### ISSUE TITLE
Prayer of collaboration!

### ISSUE THREAD

**Issue by brightplastik** [brightplastik/AR300-WiFiPineapple-2019#1]
@4dvn  , please, share with us all you know to make this become a repo for AR300M as well as AR150.
With explanations, I can try and fork it!

**Comment by brightplastik** [comment]
@4dvn , any little suggestion? I have the rootfs folders extracted from the 2 firmwares, ready to be merged. Can you tell me what goes where?
I think this is going to be very useful to many, besides me!
Let's do a good action! 

Waiting for your reply!

**Comment by 4dvn** [comment]
> @4dvn , any little suggestion? I have the rootfs folders extracted from the 2 firmwares, ready to be merged. Can you tell me what goes where?
> I think this is going to be very useful to many, besides me!
> Let's do a good action!
> 
> Waiting for your reply!

Hello, for diy wifipineapple you need a "cloud router lenovo pwr-g60" to patch the v2.7.0

**Comment by 4dvn** [comment]
> @4dvn , any little suggestion? I have the rootfs folders extracted from the 2 firmwares, ready to be merged. Can you tell me what goes where?
> I think this is going to be very useful to many, besides me!
> Let's do a good action!
> 
> Waiting for your reply!

You can't use AR300M because hak5 hardware use AR9331!

**Comment by brightplastik** [comment]
Hello @4dvn , there are examples online that prove it is possible, but are old versions.
See:
https://github.com/q-a-z/gl-ar300m-wifipineapple
And
https://raimond.at/de/pineapple-firmware-242-for-gl-ar300m-nwo-with-working-pineap/

Given these, I would like to understand how to make a 2.7.0 version and share it here on github.
You said you know how to do it!
Can you tell me how?
